title:              Swimming In Data
email:              the.brian.johns@gmail.com
description:        Brian Johns - Data Science Portfolio
author:             Brian Johns
baseurl:            ""
url:                "https://thebrianjohns.github.io"

# Social Profiles
twitter_username:   thebrianjohns
github_username:    thebrianjohns
facebook_username:  
instagram_username:  thebrianjohns
linkedin_username:   thebrianjohns

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
